{
    container: HTMLDivElement {
      '__reactContainere$ygwdd58itm': FiberNode {
        tag: 3,
        key: null,
        elementType: null,
        type: null,
        stateNode: [FiberRootNode],
        return: null,
        child: null,
        sibling: null,
        index: 0,
        ref: null,
        pendingProps: null,
        memoizedProps: null,
        updateQueue: [Object],
        memoizedState: null,
        dependencies: null,
        mode: 0,
        effectTag: 0,
        nextEffect: null,
        firstEffect: null,
        lastEffect: null,
        expirationTime: 1073741823,
        childExpirationTime: 0,
        alternate: [FiberNode],
        actualDuration: 0,
        actualStartTime: -1,
        selfBaseDuration: 0,
        treeBaseDuration: 0,
        _debugID: 37,
        _debugIsCurrentlyTiming: false,
        _debugSource: null,
        _debugOwner: null,
        _debugNeedsRemount: false,
        _debugHookTypes: null
      },
      _reactRootContainer: ReactDOMBlockingRoot { _internalRoot: [FiberRootNode] },
      [Symbol(SameObject caches)]: [Object: null prototype] { childNodes: NodeList {} }
    },
    baseElement: HTMLBodyElement {
      [Symbol(SameObject caches)]: [Object: null prototype] { childNodes: NodeList {} }
    },
    debug: [Function: debug],
    unmount: [Function: unmount],
    rerender: [Function: rerender],
    asFragment: [Function: asFragment],
    queryAllByLabelText: [Function: bound queryAllByLabelText],
    getAllByLabelText: [Function: bound getAllByLabelText],
    queryByLabelText: [Function: bound ],
    getByLabelText: [Function: bound ],
    findAllByLabelText: [Function: bound ],
    findByLabelText: [Function: bound ],
    queryByPlaceholderText: [Function: bound ],
    queryAllByPlaceholderText: [Function: bound bound queryAllByAttribute],
    getByPlaceholderText: [Function: bound ],
    getAllByPlaceholderText: [Function: bound ],
    findAllByPlaceholderText: [Function: bound ],
    findByPlaceholderText: [Function: bound ],
    queryAllByText: [Function: bound queryAllByText],
    queryByText: [Function: bound ],
    getByText: [Function: bound ],
    getAllByText: [Function: bound ],
    findAllByText: [Function: bound ],
    findByText: [Function: bound ],
    queryAllByDisplayValue: [Function: bound queryAllByDisplayValue],
    queryByDisplayValue: [Function: bound ],
    getByDisplayValue: [Function: bound ],
    getAllByDisplayValue: [Function: bound ],
    findAllByDisplayValue: [Function: bound ],
    findByDisplayValue: [Function: bound ],
    queryAllByAltText: [Function: bound queryAllByAltText],
    queryByAltText: [Function: bound ],
    getByAltText: [Function: bound ],
    getAllByAltText: [Function: bound ],
    findAllByAltText: [Function: bound ],
    findByAltText: [Function: bound ],
    queryAllByTitle: [Function: bound queryAllByTitle],
    queryByTitle: [Function: bound ],
    getByTitle: [Function: bound ],
    getAllByTitle: [Function: bound ],
    findAllByTitle: [Function: bound ],
    findByTitle: [Function: bound ],
    queryAllByRole: [Function: bound queryAllByRole],
    queryByRole: [Function: bound ],
    getAllByRole: [Function: bound ],
    getByRole: [Function: bound ],
    findAllByRole: [Function: bound ],
    findByRole: [Function: bound ],
    queryByTestId: [Function: bound ],
    queryAllByTestId: [Function: bound queryAllByTestId],
    getByTestId: [Function: bound ],
    getAllByTestId: [Function: bound ],
    findAllByTestId: [Function: bound ],
    findByTestId: [Function: bound ]
  }
